### ISSUE TITLE
Need to fix Event selection option issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#35] opened 2021-02-24 09:53 UTC
Need to fix the Event selection option issue because right now I can not see any event selection issue while generatinging the API key.

![image](https://user-images.githubusercontent.com/35419531/108982635-041afb00-76b4-11eb-82ef-8caf9dd8ce13.png)

**Comment by hiteshmakvana** [comment] 2021-03-01 12:53
Duplicate of #31

**Closed by hiteshmakvana** 2021-03-01 12:53 UTC
Labels: duplicate
